const accounts = [
  {
    id: '1',
    UserId: '1',
    title: 'Seth in Paris',
    description:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been.',
    category: 'category',
    currency: 'USD',
    availableAmount: 20000,
    dateOfCreation: new Date().toString(),
    dateOfUpdate: new Date().toString(),
  },
  {
    id: '2',
    UserId: '3',
    title: 'Judith in New York',
    description: 'Lorem Ipsum is simply dummy text of the printing and book.',
    category: 'category',
    currency: 'EUR',
    availableAmount: 80000,
    dateOfCreation: new Date().toString(),
    dateOfUpdate: new Date().toString(),
  },
  {
    id: '3',
    UserId: '4',
    title: 'Nicolas in Paris',
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's ",
    category: 'category',
    currency: 'USD',
    availableAmount: 100000,
    dateOfCreation: new Date().toString(),
    dateOfUpdate: new Date().toString(),
  },
  {
    id: '4',
    UserId: '5',
    title: 'Kyle in rome',
    description:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry',
    category: 'category',
    currency: 'GEL',
    availableAmount: 598200,
    dateOfCreation: new Date().toString(),
    dateOfUpdate: new Date().toString(),
  },
  {
    id: '5',
    UserId: '2',
    title: 'Jakeen in london',
    description: 'Lorem Ipsum is simply dummy text of the printing and ',
    category: 'category',
    currency: 'EUR',
    availableAmount: 250000,
    dateOfCreation: new Date().toString(),
    dateOfUpdate: new Date().toString(),
  },
];

const categories = [
  {
    id: '1',
    title: 'title1',
    type: 'type1',
  },
  {
    id: '2',
    title: 'title2',
    type: 'type2',
  },
];

const currencies = [
  {
    id: '1',
    name: 'USD',
    sign: 'usd.svg',
  },
  {
    id: '2',
    name: 'GEL',
    sign: 'gel.svg',
  },
  {
    id: '3',
    name: 'EUR',
    sign: 'eur.svg',
  },
];

const obligatoryPayments = [
  {
    id: '1',
    userId: '2',
    title: 'title1',
    description: 'desc1',
    amount: 500,
    currency: 'gel',
    dayOfPayment: new Date().toString(),
    frequency: 'high',
    dateOfTheFirstPayment: new Date().toString(),
    dateOfThelastPayment: new Date().toString(),
    createdOn: new Date().toString(),
    updatedOn: new Date().toString(),
  },
];

const subscriptions = [
  {
    id: '1',
    accountId: '1',
    firstDayOfPayment: new Date().toString(),
    LastDayOfPayment: new Date().toString(),
    DayOfPayment: new Date().toString(),
    category: 'category',
    currency: 'EUR',
    amount: 200,
    dateOfCreation: new Date().toString(),
    dateOfUpdate: new Date().toString(),
  },
  {
    id: '2',
    accountId: '5',
    firstDayOfPayment: new Date().toString(),
    LastDayOfPayment: new Date().toString(),
    DayOfPayment: new Date().toString(),
    category: 'category',
    currency: 'USD',
    amount: 1200,
    dateOfCreation: new Date().toString(),
    dateOfUpdate: new Date().toString(),
  },
  {
    id: '3',
    accountId: '2',
    firstDayOfPayment: new Date().toString(),
    LastDayOfPayment: new Date().toString(),
    DayOfPayment: new Date().toString(),
    category: 'category',
    currency: 'GEL',
    amount: 3000,
    dateOfCreation: new Date().toString(),
    dateOfUpdate: new Date().toString(),
  },
  {
    id: '4',
    accountId: '4',
    firstDayOfPayment: new Date().toString(),
    LastDayOfPayment: new Date().toString(),
    DayOfPayment: new Date().toString(),
    category: 'category',
    currency: 'EUR',
    amount: 800,
    dateOfCreation: new Date().toString(),
    dateOfUpdate: new Date().toString(),
  },
  {
    id: '5',
    accountId: '3',
    firstDayOfPayment: new Date().toString(),
    LastDayOfPayment: new Date().toString(),
    DayOfPayment: new Date().toString(),
    category: 'category',
    currency: 'USD',
    amount: 2900,
    dateOfCreation: new Date().toString(),
    dateOfUpdate: new Date().toString(),
  },
];

const transactions = [
  {
    id: '1',
    type: 'sales',
    accountId: '2',
    title: 'title1',
    description: 'admin',
    dateOfOperation: new Date().toString(),
    category: 'asd',
    currency: 'USD',
    amount: 1000,
    linkToFile: 'http://example.com',
    dateOfCreation: new Date().toString(),
    dateOfUpdate: new Date().toString(),
  },
  {
    id: '2',
    type: 'sales',
    accountId: '1',
    title: 'title2',
    description: 'admin',
    dateOfOperation: new Date().toString(),
    category: 'asd',
    currency: 'USD',
    amount: 1000,
    linkToFile: 'http://example.com',
    dateOfCreation: new Date().toString(),
    dateOfUpdate: new Date().toString(),
  },
  {
    id: '3',
    type: 'sales',
    accountId: '5',
    title: 'title3',
    description: 'admin',
    dateOfOperation: new Date().toString(),
    category: 'asd',
    currency: 'USD',
    amount: 1000,
    linkToFile: 'http://example.com',
    dateOfCreation: new Date().toString(),
    dateOfUpdate: new Date().toString(),
  },
  {
    id: '4',
    type: 'sales',
    accountId: '3',
    title: 'title4',
    description: 'admin',
    dateOfOperation: new Date().toString(),
    category: 'asd',
    currency: 'USD',
    amount: 1000,
    linkToFile: 'http://example.com',
    dateOfCreation: new Date().toString(),
    dateOfUpdate: new Date().toString(),
  },
  {
    id: '5',
    type: 'sales',
    accountId: '4',
    title: 'title5',
    description: 'admin',
    dateOfOperation: new Date().toString(),
    category: 'asd',
    currency: 'USD',
    amount: 1000,
    linkToFile: 'http://example.com',
    dateOfCreation: new Date().toString(),
    dateOfUpdate: new Date().toString(),
  },
];

const users = [
  {
    id: '1',
    email: 'nullam.velit@aol.net',
    password: 'Seth123',
    role: 'user',
    firstName: 'Seth',
    lastName: 'Kennedy',
    gender: 'male',
    dateOfBirth: 'United States',
    countryOfResidence: 'United States',
  },
  {
    id: '2',
    email: 'varius.orci.in@icloud.edu',
    password: 'Jakeem123',
    role: 'user',
    firstName: 'Jakeem',
    lastName: 'Patel',
    gender: 'male',
    dateOfBirth: new Date().toString(),
    countryOfResidence: 'Austria',
  },
  {
    id: '3',
    email: 'diam.sed.diam@yahoo.ca',
    password: 'Judith123',
    role: 'user',
    firstName: 'Judith',
    lastName: ' Adkins',
    gender: 'female',
    dateOfBirth: new Date().toString(),
    countryOfResidence: 'South Korea',
  },
  {
    id: '4',
    email: 'sollicitudin.commodo@outlook.edu',
    password: 'Nicholas123',
    role: 'user',
    firstName: 'Nicholas',
    lastName: 'Lester',
    gender: 'male',
    dateOfBirth: new Date().toString(),
    countryOfResidence: 'Mexico',
  },
  {
    id: '5',
    email: 'vitae.odio.sagittis@hotmail.org',
    password: 'Kylie123',
    role: 'admin',
    firstName: 'Kylie',
    lastName: 'Boone',
    gender: 'male',
    dateOfBirth: new Date().toString(),
    countryOfResidence: 'Norway',
  },
];

module.exports = {
  users,
  accounts,
  transactions,
  categories,
  currencies,
  subscriptions,
  obligatoryPayments,
};
